### ISSUE TITLE
[Bug] Falsches Namensschema 

### ISSUE THREAD

**Issue by Witteborn** [HWR-Berlin-SWE-I-Gruppe-2-Team-3-2021/Genderly#10]
# The Issue
Das abzugebende Artefakt ist nicht nach dem vorgegebenen Namensschema benannt.

- [x] Prototyp_IT20_KursB_Team8

**Comment by MK2112** [comment]
Verhält sich wie bei HWR-Berlin-SWE-I-Gruppe-2-Team-3-2021/Dokumentation#26
